plugins {
    id 'buildlogic.java-library-conventions'
    id 'buildlogic.java-publish-conventions'
}

dependencies {
    api project(':formatter')
    api project(':analyzer')
    implementation 'com.fasterxml.jackson.dataformat:jackson-dataformat-toml:2.22.1'
    implementation project(':syntax')
    implementation project(':semantics')
    implementation project(':interpreter')
    implementation project(':lexer')
}
