plugins {
    id 'buildlogic.java-library-conventions'
    id 'buildlogic.java-publish-conventions'
}

dependencies {
    api project(':formatter')
    api project(':analyzer')
    api project(':interpreter')
    implementation 'com.fasterxml.jackson.core:jackson-databind:2.17.2'
    implementation project(':syntax')
    implementation project(':parser')
    implementation project(':semantics')
    implementation project(':lexer')
}
