[case]
name = "interpreter happy path"
command = "execute"
source = "happy_path.pisp"
version = "1.0"
success = true

[expected]
stdout = [
  "Joe Doe",
  "Result: 3",
  "Remaining: 4",
]
diagnostics = []
