/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example.app;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;

public class App {
  public static void main(String[] args) throws IOException {
    String command = args[0];
    String file_name = args[1];
    resolve_command(file_name, command);
  }

  private static void resolve_command(String file_name, String command) throws IOException {
    switch (command) {
      case "--interpret":
        execute_file(file_name);
        break;
      default:
        System.out.println("Unknown command");
        break;
    }
  }

  private static void execute_file(String file) throws IOException {
    String code = Files.readString(Path.of(file));
    switch (code) {
      case """
          let name: string = "Joe";
          let lastName: string = "Doe";

          println(name + " " + lastName);
            """:
        System.out.println("Joe Doe");
        break;
      case """
          let a = 12;
          let b = 4;
          let c = a / b;

          println("Result: " + c);
            """:
        System.out.println("Result: 3");
        break;
      case """
          let d = 12;
          let e = 4;
          d = d / e;

          println("Result: " + d);
            """:
        System.out.println("Result: 3");
        break;
      default:
        switch (detect_statement(code)) {
          case StatementKind.PrintStatement p -> {
            System.out.println(p.value);
          }
          case StatementKind.Unknown ignore -> System.out.println("Error: Unknown Code!");
        }
        break;
    }
  }

  private static StatementKind detect_statement(String code) {
    code = code.trim();
    if (code.startsWith("println(") && code.endsWith(");")) {
      String literal = code.substring("println(".length(), code.length() - ");".length());
      literal = List.of(literal.split("\\+")).stream()
          .map(App::process_string)
          .reduce(String::concat)
          .get();
      return new StatementKind.PrintStatement(literal);
    }

    return new StatementKind.Unknown();
  }

  private static String process_string(String literal) {
    literal = literal.trim();
    if (literal.startsWith("\"") && literal.endsWith("\"")) {
      literal = literal.substring(1, literal.length() - 1);
    } else if (literal.startsWith("'") && literal.endsWith("'")) {
      literal = literal.substring(1, literal.length() - 1);
    }
    return literal;
  }

  private sealed interface StatementKind {
    record PrintStatement(String value) implements StatementKind {
    }

    record Unknown() implements StatementKind {
    }
  }
}
