/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example.app;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertDoesNotThrow;

import java.io.ByteArrayOutputStream;
import java.io.PrintStream;

class MessageUtilsTest {
  @Test
  void testAppDoesNotCrashes() {
    assertDoesNotThrow(() -> {
      String[] args = new String[] { "--interpret", "test_001.pisp", "--version", "1.0" };
      App.main(args);
      args = new String[] { "--format", "test.pisp", "--version", "1.0", "--format-config", "format-config.toml" };
      App.main(args);
      args = new String[] { "--analyze", "test.pisp", "--version", "1.0", "--analyze-config", "analyze-config.toml" };
      App.main(args);
      args = new String[] { "--analyze", "test.pisp", "--version", "1.0", "--format-config", "format-config.toml",
          "--analyze-config", "analyze-config.toml" };
      App.main(args);
    });
  }

  @Test
  void testAppInterpretOutput() {
    ByteArrayOutputStream virtualOutputStream = new ByteArrayOutputStream();
    PrintStream originalTerminal = System.out;
    try {
      System.setOut(new PrintStream(virtualOutputStream));

      String[] args = new String[] { "--interpret", "test_001.pisp", "--version", "1.0" };
      App.main(args);
      String printedResults = virtualOutputStream.toString().trim();
      Assertions.assertTrue(printedResults.contains("Joe Doe"));
      args = new String[] { "--interpret", "test_002.pisp", "--version", "1.0" };
      App.main(args);
      printedResults = virtualOutputStream.toString().trim();
      Assertions.assertTrue(printedResults.contains("Result: 3"));
    } finally {
      System.setOut(originalTerminal);
    }
  }

}
