name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch: {}
  workflow_call: {}

concurrency:
  group: ci-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build:
    name: Build
    uses: ./.github/workflows/build.yml

  format:
    name: Format
    uses: ./.github/workflows/format.yml

  checkstyle:
    name: Checkstyle
    needs: build
    uses: ./.github/workflows/checkstyle.yml

  pmd:
    name: PMD
    needs: build
    uses: ./.github/workflows/pmd.yml

  test:
    name: Test
    needs: build
    uses: ./.github/workflows/test.yml
